---
- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Install PyMySQL Ansible dependency
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Set MySQL primary bind address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address = {{ mysql_bind_address }}"
  notify: restart mysql

- name: Deploy MySQL primary configuration
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/99-sre-ha.cnf
    mode: '0644'
  notify: restart mysql

- name: Ensure MySQL running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create replication user
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    priv: "*.*:REPLICATION SLAVE"
    host: '%'
    state: present
  no_log: true
